version: '3'
services:
  web:
    env_file:
      - .env
    container_name: ${WEB_HOST}
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      FLASK_RUN_HOST: 0.0.0.0
      TEMPLATES_AUTO_RELOAD: 'True'
      FLASK_ENV: development
    ports: 
      - '5000:5000'
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - network

  mongodb:
    image: mongo:4.4.21
    env_file:
      - .env
    container_name: ${MONGO_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - network

volumes:
  mongo-volume:
networks:
  network:
